version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    ports:
      - 80:80
      - 443:443
    networks:
      - main
    depends_on:
      - payload

  next:
    image: node:18
    ports:
      - "3000:3000"
    volumes:
      - ./next-app:/home/node/app
    working_dir: /home/node/app/
    command: sh -c "npm run start"
    depends_on:
      - payload
    networks:
      - main

  payload:
    image: node:18
    ports:
      - "3001:3001"
    volumes:
      - ./payload-app:/home/node/app
    working_dir: /home/node/app/
    command: sh -c "npm run serve"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3001
      PAYLOAD_SECRET: TESTING
    networks:
      - main

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - main

networks:
  main:

volumes:
  data:
